### ISSUE TITLE
In ios, can this plugin works when you set the css property- 'overflow-scrolling: tounch;'?

### ISSUE THREAD

**Issue by foreverOnTheWay** [happy-js/vue-happy-scroll#1]
As we know, when we set this css property and let the list scroll, the ios will forbid many actions.
So I wanna know whether this plugin can works in ios webview.
   thx.

**Comment by tangdaohai** [comment]
@foreverOnTheWay  Hi, I'm sorry. the current version of the SP support unfriendly.I have not tested on the ios yet.
