### ISSUE TITLE
窗口变化后，happy-scroll-container的宽高没有响应

### ISSUE THREAD

**Issue by cheaprYang** [happy-js/vue-happy-scroll#11]
在使用组件的时候，组件父级宽度改变了，但是happy-scroll-container的宽高没有随父级宽高响应，

**Comment by tangdaohai** [comment]
当前版本还不支持这个功能。 #2 #6

**Comment by cheaprYang** [comment]
我已经解决了

**Comment by ColinCLL** [comment]
@cheaprYang 怎么解决的？

**Comment by tangdaohai** [comment]
@ColinCLL 目前版本可以自己监听父级窗口的 resize 事件，然后通过`ref`调用下`mounted`里面的方法:https://github.com/tangdaohai/vue-happy-scroll/blob/15aa8509bf5b4d2b5cf31bdbdacd1438198129ab/src/scroll.vue#L291
