### ISSUE TITLE
当内容比较的时候，滚动条很短，而且滚动条在底部

### ISSUE THREAD

**Issue by coderew** [happy-js/vue-happy-scroll#13]
当内容比较的时候，滚动条很短，而且滚动条在底部
![image](https://user-images.githubusercontent.com/20498067/42009580-8fd24770-7abd-11e8-925c-2083ba4d2e02.png)

**Comment by caktye** [comment]
我也发现了，原生的滚动条是当内容超过一定高度，滚动条的会有个最小高度。
![image](https://user-images.githubusercontent.com/16329491/42025636-a2faedae-7af7-11e8-9af6-bcf11b652325.png)
试了给滚动条增加最小高度，但是事件判断改不到。。。滚动条跳出容器框
![image](https://user-images.githubusercontent.com/16329491/42025734-dc04de84-7af7-11e8-8eb5-50066731e393.png)

**Comment by tangdaohai** [comment]
谢谢反馈。 @coderew @caktye 
最近在计划，更新一个大版本，我会把这个功能加进去。
