### ISSUE TITLE
求助啊.非常急

### ISSUE THREAD

**Issue by yuansudong** [happy-js/vue-happy-scroll#15]
vue-happy-scroll  当浏览器小窗口打开的时候, 页面布置好了,当点击浏览器全屏的时候,这个时候,在vue-happy-scroll中的元素快,并不会跟着缩放,而不在happy-scroll中的元素就缩放了, 用resize 也没效果, 请问,我应该如何解决?

**Comment by tangdaohai** [comment]
@yuansudong 当前版本还不支持容器的 resize。下个版本会计划加入此功能。 #2

**Comment by yuansudong** [comment]
谢谢
