### ISSUE TITLE
父级容器大小发生变化，滚动会不正确

### ISSUE THREAD

**Issue by liunewshine** [happy-js/vue-happy-scroll#2]
父级容器高度是100vh，缩小浏览器高度，父级容器高度会发生变化。
此时会无法滚动到底部，加了resize也无效
![image](https://user-images.githubusercontent.com/7698511/33512920-c7dfae5c-d773-11e7-99af-9079c380212b.png)

**Comment by tangdaohai** [comment]
@liunewshine 你好，当前版本，还没有对容器大小变化做监听处理。`resize` 属性是监听`happy-scroll`内部元素的大小变化，也就是你图片中的`.logo`元素。

所以你需要将你的`.sidebar`元素做一个固定宽高的设置，或者对`<hayyp-scroll>`元素进行固定宽高设置。

当然，我会把这个功能加入到feature list中，未来会支持它的。

**Comment by liunewshine** [comment]
了解
