### ISSUE TITLE
当窗口大小改变时，happy-scroll-container不会自适应，怎么处理？

### ISSUE THREAD

**Issue by Doyouwannago** [happy-js/vue-happy-scroll#3]
![qq 20171211140558](https://user-images.githubusercontent.com/22318083/33817829-931e4e66-de7c-11e7-9081-d10d07cbf501.png)

**Comment by tangdaohai** [comment]
@Doyouwannago 如果我没有理解错误，你的问题应该与这个问题一样的 [#2](https://github.com/happy-js/vue-happy-scroll/issues/2)
